# Generated by Codex on 2026-02-08

from django.db import migrations, models
from django.db.models import F


def convert_hourly_to_monthly(apps, schema_editor):
    EmployeeProfile = apps.get_model('accounts', 'EmployeeProfile')
    EmployeeProfile.objects.exclude(monthly_salary__isnull=True).update(
        monthly_salary=F('monthly_salary') * 120
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_employeeshiftrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='hourly_rate',
            new_name='monthly_salary',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='hourly_rate_reason',
            new_name='salary_reason',
        ),
        migrations.RunPython(
            code=convert_hourly_to_monthly,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='weekly_hours_norm',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
