# Generated by Django 5.2.10 on 2026-02-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_salary_and_weekly_norm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshiftrequest',
            name='request_type',
            field=models.CharField(choices=[('extra_hours', 'Дополнительные часы'), ('replacement', 'Замена слота')], max_length=20),
        ),
    ]
