# Generated by Django 5.2.10 on 2026-02-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_tasksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttask',
            name='task_type',
            field=models.CharField(choices=[('employee', 'Сотруднику'), ('slot', 'Для слота'), ('department', 'Для отдела')], default='employee', max_length=20),
        ),
    ]
